/* Generated by Yosys 0.32+74 (git sha1 b739213d9, gcc 12.3.0-1ubuntu1~22.04 -fPIC -Os) */

module d_ff(clk, d, rst, q);
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  reg q;
  input rst;
  wire rst;
  always @(posedge clk)
    if (rst) q <= 1'h0;
    else q <= d;
endmodule

module pes_sipo(clk, b, q);
  input b;
  wire b;
  input clk;
  wire clk;
  output [3:0] q;
  wire [3:0] q;
  d_ff dut1 (
    .clk(clk),
    .d(b),
    .q(q[3])
  );
  d_ff dut2 (
    .clk(clk),
    .d(q[3]),
    .q(q[2])
  );
  d_ff dut3 (
    .clk(clk),
    .d(q[2]),
    .q(q[1])
  );
  d_ff dut4 (
    .clk(clk),
    .d(q[1]),
    .q(q[0])
  );
endmodule
